# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias dir='la -la'
alias la='ls -ltra'
alias poweroff='shutdown -h now'
alias restart='shutdown -h now'
alias mt='mvn test'
alias mtc='mvn test -Pacceptance'
alias mta='mvn test -Dtest=RunAllScenario'
alias mtw='mvn test -Dtest=RunWipScenario'
alias mp='mvn package'
alias mcp='mvn clean package'
alias mcpst='mvn clean package -DskipTests'
alias sd='shutdown -h now; sleep 2; exit'
alias dp="sh deploy.sh"
alias mee='mvn eclipse:eclipse'
alias sb='cd $WS/cps-sandbox'
alias gh='less ~/.gitconfig'
alias ghml='cp -rf ~/.gcml ~/.gitconfig'
alias ghjml='cp -rf ~/.gcjml ~/.gitconfig'
alias gs='git status'
